### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by JacksonChen666** [RayMarch/ferris3d#2]
This project has a license declared in the README, but not a LICENSE file. I suggest adding it for very clear visibility.

**Comment by RayMarch** [comment]
good point, i agree. 
I wonder if there is a `LICENSE.txt` that makes Github show "public domain" or something similar directly in the overview (kind of how it does with MIT)

**Comment by JacksonChen666** [comment]
@RayMarch so basically what you do is [include the full legal terms](https://github.com/RayMarch/ferris3d/community/license/new?branch=main&filename=LICENSE&template=cc0-1.0) and it should work (GitHub will fallback to "View license" if it doesn't understand which license it is)

**Comment by RayMarch** [comment]
thank you for that link. I added the license file 👍.
